Repository enflujo/enflujo-haciendocaminos, pull requests merged in 2024-03, with the labels that each got.

#71 💅🏼color buscador, botón créditos, estilos varios y pata logos
  src/componentes/Buscador.astro
  src/componentes/Cabezote.astro
  src/componentes/Creditos.astro
  src/componentes/Ficha.astro
  src/componentes/PataLogos.astro
  src/pages/egresados.astro
  src/pages/index.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
Labels: ui :ocean:

#75 ✍🏼 correcciones que Lucho mandó por WhatsApp
  estaticos/imgs/60-anos_blanco.svg
  estaticos/imgs/logo-humanidadDigital.svg
  estaticos/imgs/logo_andes_blanco.svg
  estaticos/imgs/uniandes_guardaescobas_negro.svg
  src/componentes/Cabezote.astro
  src/componentes/Creditos.astro
  src/componentes/PataLogos.astro
Labels: front-end :art:, ui :ocean:

#79 ✨ Correcciones Lucho 13-03-24
  procesador/datos/Listado de proyectos - 60 años dpto antropología .xlsx
  src/componentes/Creditos.astro
  src/componentes/Ficha.astro
  src/tipos.ts
  src/utilidades/cerebro.ts
Labels: mejora :ant:

#90 ✨ Agregar interacción desde mapa
  estaticos/datosMapa.geo.json
  estaticos/datosMapaEgresados.geo.json
  procesador/lugares.ts
  src/componentes/Ficha.astro
  src/componentes/Mapa.astro
  src/scss/estilos.scss
  src/utilidades/cerebro.ts
Labels: ui :ocean:
