Repository enflujo/enflujo-haciendocaminos, pull requests merged in 2024-02, with the labels that each got.

#13 🗺️ Procesar geojson y pintar puntos en el mapa
  estaticos/datosMapa.geo.json
  estaticos/listas.json
  estaticos/proyectos.json
  estaticos/prueba.geo.json
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología .xlsx#
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología2901 .xlsx#
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología3101.xlsx#
  procesador/Listado de proyectos - 60 años dpto antropología2402.xlsx
  procesador/Listado de proyectos - 60 años dpto antropología2901 .xlsx
  procesador/Listado de proyectos - 60 años dpto antropología3101.xlsx
  procesador/ayudas.ts
  procesador/procesador.ts
  src/componentes/Ficha.astro
  src/componentes/Mapa.astro
  src/pages/index.astro
  src/tipos.ts
Labels: api :evergreen_tree:, front-end :art:

#14 🖌️ Estilos parte 1
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología .xlsx#
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología2901 .xlsx#
  procesador/.~lock.Listado de proyectos - 60 años dpto antropología3101.xlsx#
  src/componentes/Cabezote.astro
  src/componentes/Ficha.astro
  src/componentes/ListaNodos.astro
  src/pages/index.astro
  src/scss/_constantes.scss
Labels: front-end :art:

#15 🗂️ Estilo ficha técnica
  src/componentes/Ficha.astro
  src/componentes/ListaNodos.astro
  src/pages/index.astro
Labels: front-end :art:, optimización :zap:

#16 ✨ Ficha técnica en tamaños de pantalla pequeña y grande
  src/componentes/Ficha.astro
Labels: front-end :art:

#21 🐛 letras, márgenes y otras cositas
  src/componentes/Ficha.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
Labels: ui :ocean:

#23 ✏️ Componente introducción
  src/componentes/Ficha.astro
  src/componentes/Introduccion.astro
  src/componentes/LineaTiempo.astro
  src/componentes/ListaNodos.astro
  src/pages/index.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
Labels: front-end :art:, optimización :zap:

#22 😵 Mostrar proyectos
  estaticos/listas.json
  estaticos/proyectos.json
  package.json
  procesador/Listado de proyectos - 60 años dpto antropología0802.xlsx
  procesador/procesador.ts
  procesador/~$Listado de proyectos - 60 años dpto antropología0802.xlsx
  src/componentes/Cabezote.astro
  src/componentes/Ficha.astro
  src/componentes/Introduccion.astro
  src/componentes/LineaTiempo.astro
  src/componentes/ListaNodos.astro
  src/componentes/Listas.astro
  src/componentes/Mapa.astro
  src/componentes/Proyectos.astro
  src/pages/index.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
  src/tipos.ts
  src/utilidades/cerebro.ts
  yarn.lock
Labels: front-end :art:

#27 🐈 Nueva estructura datos
  estaticos/listas.json
  estaticos/proyectos.json
  procesador/ayudas.ts
  procesador/datos/Listado de proyectos - 60 años dpto antropología .xlsx
  procesador/datos/Listado de proyectos - 60 años dpto antropología0802.xlsx
  procesador/datos/Listado de proyectos - 60 años dpto antropología2402.xlsx
  procesador/lugares.ts
  procesador/procesador.ts
  procesador/~$Listado de proyectos - 60 años dpto antropología0802.xlsx
  src/componentes/Ficha.astro
  src/componentes/ListaNodos.astro
  src/componentes/Listas.astro
  src/tipos.ts
  src/utilidades/cerebro.ts
  src/utilidades/lugares.ts
Labels: api :evergreen_tree:, front-end :art:

#32 ❄️ Galeria en proceso
  package.json
  src/componentes/Ficha.astro
  src/scss/estilos.scss
  yarn.lock
Labels: front-end :art:

#41 🏓 Mapa egresados
  estaticos/datosMapa.geo.json
  estaticos/datosMapaEgresados.geo.json
  estaticos/egresados.json
  estaticos/listas.json
  estaticos/listasEgresados.json
  estaticos/proyectos.json
  procesador/datos/Listado de proyectos - 60 años dpto antropología 1902.xlsx
  procesador/egresados.ts
  procesador/lugares.ts
  procesador/procesador.ts
  src/componentes/Mapa.astro
  src/pages/egresados.astro
  src/pages/index.astro
  src/utilidades/cerebro.ts
Labels: front-end :art:

#45 🐛 Corregir estilos en lista egresados y ficha
  src/scss/estilos.scss
Labels: bicho :bug:

#49 🐛 Arreglar bichos en mapa y en lista
  src/componentes/Cabezote.astro
  src/componentes/Introduccion.astro
  src/componentes/Proyectos.astro
  src/scss/estilos.scss
  src/utilidades/ayudas.ts
  src/utilidades/cerebro.ts
Labels: bicho :bug:, front-end :art:

#53 🐛 cositas de estilos y gusanitos
  src/componentes/Cabezote.astro
  src/componentes/EgresadosNombres.astro
  src/componentes/Ficha.astro
  src/componentes/Proyectos.astro
  src/scss/estilos.scss
Labels: ui :ocean:

#66 💄 Correcciones varias
  src/componentes/EgresadosNombres.astro
  src/componentes/Ficha.astro
  src/componentes/Proyectos.astro
  src/pages/egresados.astro
  src/plantillas/Plantilla.astro
  src/scss/estilos.scss
  src/utilidades/cerebro.ts
Labels: bicho :bug:, front-end :art:

#68 🕐 Nuevio diseño Linea tiempo
  src/componentes/Introduccion.astro
  src/componentes/LineaTiempo.astro
  src/pages/index.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
Labels: front-end :art:

#69 🌱 favicon, parte del SEO, créditos y ajustes estilo
  estaticos/apple-touch-icon.png
  estaticos/favicon.ico
  estaticos/favicon.svg
  estaticos/icono_192.png
  estaticos/icono_512.png
  estaticos/imgs/logo_enflujo_blanco.svg
  estaticos/sitio.webmanifest
  src/componentes/Cabezote.astro
  src/componentes/Creditos.astro
  src/pages/index.astro
  src/plantillas/Plantilla.astro
Labels: ui :ocean:

#70 ☎️ Celulares
  estaticos/imgs/lupa.svg
  src/componentes/Buscador.astro
  src/componentes/Cabezote.astro
  src/componentes/LineaTiempo.astro
  src/componentes/Proyectos.astro
  src/scss/_constantes.scss
  src/scss/estilos.scss
Labels: front-end :art:, ui :ocean:
